# -*- coding: utf-8 -*-
"""TLe-HW2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JedepbZ28fNmqo8LuDKTlwOXpQZz3lFO

# MILP Problem

Tien Le - 84820499

Script format based off of milp_ffnn.py by Dung Tran
"""

import numpy as np
from scipy.optimize import milp, Bounds, LinearConstraint
import time

start_time = time.time()
# coefficient of the object function to be minimized: z3 = -z21 + 2z22
# for max z3 we minimize -c
c = np.array([0, 0, 0, -1, 2, 0, 0, 0, 0, 0, 0, 0])

# constraint matrix A: lb <= Az <= bu
# z = [z11, z12, z13, z21, z22, d11, d12, d13, d21, d22, x ,y]
# 7 continuous variables z11, z12, z13, z21, z22, x, y
# 5 integer variables d11, d12, d13, d21, d22

M11 = 2
M12 = 1
M13 = 3
M21 = 6
M22 = 1

#M = 10
# constraint matrix A: lb <= Az <= bu
A_Z11 = np.array([[-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],    # z11[1] ≥ 0
                  [-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1],   # z11[1] ≥ x - y
                  [0, 0, 0, 0, 0, -M11, 0, 0, 0, 0, 1, -1], # x - y - 2d11 <= 0
                  [0, 0, 0, 0, 0, M11, 0, 0, 0, 0, -1, 1],  # -x + y + 2d11 <= 0
                  [1, 0, 0, 0, 0, M11, 0, 0, 0, 0, -1, 1],  # z11[1] - x + y - 2(1-d11) <= 0
                  [1, 0, 0, 0, 0, -M11, 0, 0, 0, 0, 0, 0]]) # z11[1] - d11 <= 0

b_Z11 = np.array([0, 0, 0, M11, M11, 0])

A_Z12 = np.array([[0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,0],    # z12 >= 0
                  [0, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1],   # z12 + x - y >= 0
                  [0, 0, 0, 0, 0, 0, -M12, 0, 0, 0, -1, 1], #  -x + y - d12 <= 0
                  [0, 0, 0, 0, 0, 0, M12, 0, 0, 0, 1, -1],  # x - y + d12 <= 1
                  [0, 1, 0, 0, 0, 0, M12, 0, 0, 0, 1, -1],  # z12 + x - y - d12 <= 1
                  [0, 1, 0, 0, 0, 0, -M12, 0, 0, 0, 0, 0]]) # z12 - d12 <= 0

b_Z12 = np.array([0, 0, 0, M12, M12, 0])

A_Z13 = np.array([[0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],    # -z13 <=0
                  [0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, -2],   #  -z13 + x -2y <= 0
                  [0, 0, 0, 0, 0, 0, 0, -M13, 0, 0, 1, -2], # x - 2y -3d13 <= 0
                  [0, 0, 0, 0, 0, 0, 0, M13, 0, 0, -1, 2],  # -x + 2y + 3d13 <= 3
                  [0, 0, 1, 0, 0, 0, 0, M13, 0, 0, -1, 2],  # z13 - x + 2y + 3d13 <= 3
                  [0, 0, 1, 0, 0, 0, 0, -M13, 0, 0, 0, 0]]) # z13 - 3d13 <= 0

b_Z13 = np.array([0, 0, 0, M13, M13, 0])

A_Z21 = np.array([[0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],    # z21 >= 0
                  [-2, -2, 3, -1, 0, 0, 0, 0, 0, 0, 0, 0],  # z21 >= 2z11 + 2z12 - 3z13
                  [2, 2, -3, 0, 0, 0, 0, 0, -M21, 0, 0, 0], # 2z11 + 2z12 - 3z13 - 6d21 <= 0
                  [-2, -2, 3, 0, 0, 0, 0, 0, M21, 0, 0, 0], # 2z11 + 2z12 - 3z13 + 6(1-d21) >= 0
                  [-2, -2, 3, 1, 0, 0, 0, 0, M21, 0, 0, 0], # z21 <= 2z11 + 2z12 - 3z13 + 6(1-d21)
                  [0, 0, 0, 1, 0, 0, 0, 0, -M21, 0, 0, 0]]) # z21 -6d21 <= 0

b_Z21 = np.array([0, 0, 0, M21, M21, 0])


A_Z22 = np.array([[0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],      # z22 >= 0
                  [-0.5, 1, 2, 0, -1, 0, 0, 0, 0, 0, 0, 0],   # z22 >= 0.5z11 - z12 - 2z13
                  [0.5, -1, -2, 0, 0, 0, 0, 0, 0, -M22, 0, 0], # 0.5z11 - z12 - 2z13 - d22 <= 0
                  [-0.5, 1, 2, 0, 0, 0, 0, 0, 0, M22, 0, 0],  # 0.5z11 - z12 - 2z13 + M22(1-d22) >= 0
                  [-0.5, 1, 2, 0, 1, 0, 0, 0, 0, M22, 0, 0],  # z22 <= 0.5z11 - z12 - 2z13 +  M22(1-d22)
                  [0, 0, 0, 0, 1, 0, 0, 0, 0, -M22, 0, 0]])   # z22 <= d22

b_Z22 = np.array([0, 0, 0, M22, M22, 0])

# combine all constraints
A = np.concatenate((A_Z11, A_Z12, A_Z13, A_Z21, A_Z22) )

# Lower possible bounds
numb_c = len(A)
b_l = (-np.inf) * np.ones(numb_c)
# Upper bound
b_u = np.concatenate((b_Z11, b_Z12, b_Z13, b_Z21, b_Z22))

# b_l <= Az <= b_u

constraints = LinearConstraint(A, b_l, b_u)

# From naive interval approach
# Bounds on the decision variables
# z11 ~ [0, M11], z12 ~ [0, M12], z13 ~ [0, M13]
# z21 ~ [0, M21], z22 ~ [0, M22]
# x ~ [0, 1], y ~ [-1, 1]
# d11 ~ [0, 1], d12 ~ [0, 1], d13 ~ [0,1], d21 ~[0,1], d22 ~[0,1]

#  [z11, z12, z13, z21, z22, d11, d12, d13, d21, d22, x ,y]
lb = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1]
ub = [M11, M12, M13, M21, M22, 1, 1, 1, 1, 1, 1, 1]
assert len(lb) == len(ub)
bounds = Bounds(lb, ub)

# integrality: 0 -> real variable, 1 -> integer variable
integrality = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0], dtype=np.int16)

result = milp(c=c, constraints=constraints, bounds=bounds,integrality=integrality)
print("optimal value: ", result.fun)
print("optimal variables: ", result.x)
print("optimization time: %s {} seconds".format(time.time()-start_time))

